apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: simplicity-graphql
  labels:
    app: simplicity-graphql
spec:
 selector:
   matchLabels:
     app: simplicity-graphql
 replicas: 1
 template:
   metadata:
     labels:
       app: simplicity-graphql
   spec:
     containers:
     - name: simplicity-graphql
       image: conantp/simplicity-graphql-server:development
       imagePullPolicy: Always
       env:
       - name: VIRTUAL_HOST
         value: graphql.prcapps.com
       - name: dbhost
         value: 52.21.47.88
       - name: dbuser
         value: opendatauser
       - name: dbpassword
         value: opendata
       - name: database
         value: datastore1
       ports:
       - containerPort: 8080
       readinessProbe:
          httpGet:
            path: /graphiql/
            port: 8080
       livenessProbe:
          httpGet:
            path: /graphiql/
            port: 8080
     restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: simplicity-graphql
  labels:
    app: simplicity-graphql
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: simplicity-graphql
